#!/bin/bash

# 1.) Get the operating system to adjust the ~/.bashrc and ~/.bash profile files accordingly
echo "----------------------------"
OS=$(uname -s)
case "$OS" in
    Linux*) OS="Linux";;
    Darwin*) OS="macOS";;
    CYGWIN*|MINGW*) OS="Windows";;
    *) echo "Unsupported operating system: $OS"; exit 1;;
esac
echo "Detected OS: $OS"
echo "Conda is detected in: $HOME"

#2.) write the bash_profile accordingly
# 2.) Write the bash_profile accordingly
if [[ "$OS" == "Windows" ]]; then
    # Define the Conda initialization block
    CONDA_INIT_BLOCK=$(cat << 'EOF'
# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [ -f "$HOME/Anaconda3/Scripts/conda.exe" ]; then
    eval "$("$HOME/Anaconda3/Scripts/conda.exe" 'shell.bash' 'hook')"
fi
# <<< conda initialize <<<
EOF
    )

    # File to modify (.bashrc)
    BASHRC_FILE="$HOME/.bashrc"

    # Overwrite the .bashrc file with the Conda initialization block
    echo "$CONDA_INIT_BLOCK" > "$BASHRC_FILE"

    echo ">> .bashrc file has been overwritten with the Conda initialization block."
    echo "----------------------------"

fi

